---
- name: Install Flux
  ansible.builtin.include_tasks: install_flux.yml

- name: Setup GitOps
  ansible.builtin.include_tasks: setup_gitops.yml

- name: Setup Flux UI
  ansible.builtin.include_tasks: setup_ui.yml

- name: Setup Flux notifications
  ansible.builtin.include_tasks: setup_notifications.yml

- name: Setup Harbor secret
  ansible.builtin.include_tasks: setup_harbor_secret.yml