- name: Create Harbor image pull secret in each app namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: harbor-pull-secret
        namespace: "{{ item.name }}"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ lookup('template', 'harbor-dockerconfig.json.j2') | to_json | b64encode }}"
  loop: "{{ self_saas_projects }}"
