# Flux UI - weave-gitops
- name: Set bcrypt hash fact
  ansible.builtin.set_fact:
    weave_gitops_admin_password_hash: "{{ weave_gitops_admin_password | password_hash('bcrypt') }}"

- name: Install Weave GitOps (Flux UI) via Helm (OCI)
  kubernetes.core.helm:
    name: weave-gitops
    chart_ref: oci://ghcr.io/weaveworks/charts/weave-gitops
    release_namespace: flux-system
    create_namespace: false
    state: present
    values:
      adminUser:
        create: true
        createSecret: true
        username: admin
        # Use a bcrypt hash for the password (see below)
        passwordHash: "{{ weave_gitops_admin_password_hash }}"
    wait: true
    wait_timeout: "{{ helm_install_timeout }}"
