#cloud-config

users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh_authorized_keys:
      - ${SSH_PUBLIC_KEY} # Replace this with your actual public key or use envsubst in your script

package_update: true
package_upgrade: true
packages:
  - socat

runcmd:

  # Enable IP forwarding
  - sysctl -w net.ipv4.ip_forward=1
  # Set SSH to listen on port 2222 by editing sshd_config directly
  - sed -i 's/^#\?Port .*/Port 2222/' /etc/ssh/sshd_config
  # If no Port line exists, add it
  - grep -q '^Port 2222' /etc/ssh/sshd_config || echo 'Port 2222' >> /etc/ssh/sshd_config
  # Reload systemd and restart the SSH service to apply changes
  - systemctl daemon-reload
  - systemctl restart ssh.service
