site_name: Self-Host SaaS K3s
repo_url: https://github.com/humansoftware/self-host-saas-k3s
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
      - Prerequisites: prerequisites.md
      - Installation: installation.md
      - Security: security.md
  - Core Components:
      - K3s: k3s.md
      - Harbor: harbor.md
      - Longhorn: longhorn.md
  - Application Management:
      - Applications: applications.md
      - Monitoring: monitoring.md
