---
- name: Install docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

- name: Setup K3s Cluster
  hosts: k3s_cluster
  become: true
  roles:
    - k3s_cluster

- name: Configure firewall
  hosts: all
  become: true
  roles:
    - firewall
