---
- name: Check prerequisites
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Fail if HOST_PUBLIC_IP is not set
      ansible.builtin.fail:
        msg: "The environment variable HOST_PUBLIC_IP must be set before running this playbook."
      when: host_public_ip is not defined or host_public_ip == ""

- name: Configure firewall
  hosts: k3s_cluster
  become: true
  roles:
    - role: firewall
      tags: firewall

- name: Setup K3s Cluster
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: k3s_cluster
      tags: k3s_cluster

- name: Set kubeconfig path fact on localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set kubeconfig path for use on localhost
      ansible.builtin.set_fact:
        k3s_kubeconfig_path: "{{ hostvars[groups['k3s_cluster'][0]].k3s_kubeconfig_path }}"
      tags: always

- name: Install Kubernetes apps
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ k3s_kubeconfig_path }}"
  roles:
    - role: install_k8s_apps
      tags: install_k8s_apps

- name: Trust Harbor CA in containerd
  hosts: k3s_cluster
  become: true
  roles:
    - role: add_harbor_ca_certs_to_k3s
      tags: add_harbor_ca_certs_to_k3s
