---
- name: Check prerequisites
  hosts: all
  gather_facts: false
  tasks:
    - name: Fail if HOST_PUBLIC_IP is not set
      ansible.builtin.fail:
        msg: "The environment variable HOST_PUBLIC_IP must be set before running this playbook."
      when: host_public_ip is not defined or host_public_ip == ""

- name: Install docker
  hosts: all
  become: true
  roles:
    - geerlingguy.docker

- name: Setup K3s Cluster
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - k3s_cluster

- name: Set kubeconfig path fact
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Set kubeconfig path fact
      ansible.builtin.set_fact:
        my_kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"

- name: Install cert-manager
  hosts: k3s_cluster
  become: false
  environment:
    KUBECONFIG: "{{ my_kubeconfig_path }}"
  roles:
    - role: githubixx.cert-manager-kubernetes
      tags: role-cert-manager-kubernetes

- name: Configure firewall
  hosts: all
  become: true
  roles:
    - firewall
