---
- name: Check prerequisites
  hosts: k3s_cluster
  gather_facts: false
  tasks:
    - name: Fail if HOST_PUBLIC_IP is not set
      ansible.builtin.fail:
        msg: "The environment variable HOST_PUBLIC_IP must be set before running this playbook."
      when: host_public_ip is not defined or host_public_ip == ""

- name: Configure firewall
  hosts: k3s_cluster
  become: true
  roles:
    - role: firewall
      tags: firewall

- name: Setup K3s Cluster
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: k3s_cluster
      tags: k3s_cluster

- name: Configure local k3s tunnel
  hosts: localhost
  gather_facts: false
  become: false
  roles:
    - role: configure_local_k3s_tunnel
      tags: configure_local_k3s_tunnel

- name: Install Kubernetes apps
  hosts: localhost
  gather_facts: false
  become: false
  environment:
    KUBECONFIG: "{{ k3s_local_kubeconfig }}"
  vars:
    helm_install_timeout: 5m # Default timeout for Helm installations
  roles:
    - role: cert_manager
      tags: cert_manager
    - role: longhorn
      tags: longhorn
    - role: harbor
      tags: harbor
    - role: argocd
      tags: argocd
    # - role: flux
    #   tags: flux
    - role: github_actions
      tags: github_actions
    - role: monitoring
      tags: monitoring
    - role: mailu
      when: install_mailu_for_smtp
      tags: mailu
    - role: postgres
      when: install_postgres
      tags: postgres
    - role: cassandra
      when: install_cassandra
      tags: cassandra
    - role: elasticsearch
      when: install_elasticsearch
      tags: elasticsearch
    - role: create_projects_secrets
      tags: create_projects_secrets

- name: Trust Harbor CA in containerd
  hosts: k3s_cluster
  become: true
  roles:
    - role: add_harbor_ca_certs_to_k3s
      tags: add_harbor_ca_certs_to_k3s
