---
# tasks file for configure_local_k3s_tunnel
# These tasks automate the SSH tunnel and systemd user service setup for k3s
- name: Ensure ~/.ssh directory exists
  ansible.builtin.file:
    path: "~/.ssh"
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true
  become: false

- name: Create SSH tunnel config file
  ansible.builtin.template:
    src: "k3s_tunnel_config.j2"
    dest: "~/.ssh/k3s_tunnel_config"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  become: false
  vars:
    k3s_server_ip: "{{ host_public_ip }}"
    k3s_ssh_port: "{{ ssh_port_rewritten | default(2222) }}"

- name: Ensure ~/.config/systemd/user directory exists
  ansible.builtin.file:
    path: "~/.config/systemd/user"
    state: directory
    mode: '0700'
  delegate_to: localhost
  run_once: true
  become: false

- name: Create k3s-tunnel systemd user service
  ansible.builtin.template:
    src: "k3s-tunnel.service.j2"
    dest: "~/.config/systemd/user/k3s-tunnel.service"
    mode: '0644'
  delegate_to: localhost
  run_once: true
  become: false

- name: Reload systemd user daemon
  ansible.builtin.systemd_service:
    daemon_reload: true
    scope: user
  delegate_to: localhost
  run_once: true
  become: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid | default(1000) }}"

- name: Enable and start k3s-tunnel systemd user service
  ansible.builtin.systemd:
    name: k3s-tunnel
    enabled: true
    state: started
    scope: user
  delegate_to: localhost
  run_once: true
  become: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid | default(1000) }}"

- name: Enable lingering for user
  ansible.builtin.command: loginctl enable-linger {{ lookup('env', 'USER') }}
  delegate_to: localhost
  run_once: true
  become: false
  changed_when: false
  failed_when: enable_linger_result.rc not in [0,1]
  register: enable_linger_result

- name: Restart k3s-tunnel systemd user service
  ansible.builtin.systemd:
    name: k3s-tunnel
    state: restarted
    scope: user
  delegate_to: localhost
  run_once: true
  become: false
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_uid | default(1000) }}"
