- name: Ensure Longhorn namespace exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ longhorn_namespace }}"
    state: present

- name: Create Longhorn backup credential secret for Backblaze B2
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: longhorn-backblaze-secret
        namespace: "{{ longhorn_namespace }}"
      stringData:
        AWS_ACCESS_KEY_ID: "{{ backblaze_key_id }}"
        AWS_SECRET_ACCESS_KEY: "{{ backblaze_application_key }}"
        AWS_REGION: "{{ backblaze_region }}"
        AWS_ENDPOINTS: "{{ backblaze_endpoint }}"
        VIRTUAL_HOSTED_STYLE: "true"

- name: Add Longhorn Helm repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io

- name: Install Longhorn via Helm
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: 1.8.1
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    values: "{{ longhorn_helm_values }}"
    wait: true
    wait_timeout: "{{ helm_install_timeout }}"

- name: Create Longhorn StorageClass with 1 replica
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: storage.k8s.io/v1
      kind: StorageClass
      metadata:
        name: longhorn-single-replica
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "1"
        staleReplicaTimeout: "30"
        fromBackup: ""
        fsType: "ext4"
        dataLocality: "disabled"
        unmapMarkSnapChainRemoved: "ignored"
        disableRevisionCounter: "true"
        dataEngine: "v1"

- name: Create Longhorn weekly recurring backup job
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: longhorn.io/v1beta2
      kind: RecurringJob
      metadata:
        name: weekly-backup
        namespace: "{{ longhorn_namespace }}"
      spec:
        name: weekly-backup
        cron: "0 3 * * 0"
        task: backup
        groups:
          - default
        retain: 4
        concurrency: 1
