---
- name: Setup mailu namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Add Mailu Helm repo
  ansible.builtin.include_tasks: add_helm_repo.yml

- name: Setup Mailu certificates
  ansible.builtin.include_tasks: setup_certificates.yml

- name: Install Mailu
  ansible.builtin.include_tasks: install.yml

- name: Configure project domains and users in Mailu
  ansible.builtin.include_tasks: configure_project_domains.yml
  loop: "{{ self_saas_projects | default([]) }}"
  loop_control:
    loop_var: item
  when: item.mailu.enabled | default(false)
