---
- name: Setup mailu namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Add Mailu Helm repo
  ansible.builtin.include_tasks: add_helm_repo.yml

- name: Setup Mailu certificates
  ansible.builtin.include_tasks: setup_certificates.yml

- name: Install Mailu
  ansible.builtin.include_tasks: install.yml
