---
- name: Set first Mailu project fact
  ansible.builtin.set_fact:
    first_mailu_project: >-
      {{ self_saas_projects |
         selectattr('mailu.enabled', 'defined') |
         selectattr('mailu.enabled') |
         first }}
  when: self_saas_projects | selectattr('mailu.enabled', 'defined') | selectattr('mailu.enabled') | list | length > 0

- name: Set Mailu main domain and admin facts
  ansible.builtin.set_fact:
    mailu_main_domain: "{{ first_mailu_project.domain }}"
    mailu_admin_username: "{{ first_mailu_project.mailu.user }}"
    mailu_admin_password: "{{ first_mailu_project.mailu.password }}"
  when: first_mailu_project is defined and first_mailu_project is not none

- name: Setup mailu namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Add Mailu Helm repo
  ansible.builtin.include_tasks: add_helm_repo.yml

- name: Setup Mailu certificates
  ansible.builtin.include_tasks: setup_certificates.yml

- name: Install Mailu
  ansible.builtin.include_tasks: install.yml

- name: Configure project domains and users in Mailu
  ansible.builtin.include_tasks: configure_project_domains.yml
  loop: "{{ self_saas_projects | default([]) }}"
  loop_control:
    loop_var: item
  when: item.mailu.enabled | default(false)
