---
- name: Render keyspace creation SQL from template
  ansible.builtin.template:
    src: create_keyspace.cql.j2
    dest: "/tmp/create_keyspace_{{ item.name }}.cql"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create ConfigMap for keyspace creation SQL
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "create-keyspace-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
        namespace: "{{ cassandra_namespace }}"
      data:
        create_keyspace.cql: |
          {{ lookup('file', '/tmp/create_keyspace_{{ item.name }}.cql') | indent(10) }}
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Run keyspace creation SQL in a temporary Cassandra client pod
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "cassandra-keyspace-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
        namespace: "{{ cassandra_namespace }}"
      spec:
        backoffLimit: 1
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: cqlsh
                image: bitnami/cassandra:{{ cassandra_image_version }}
                command: ["cqlsh"]
                args:
                  - "-f"
                  - "/tmp/create_keyspace.cql"
                  - "cassandra"
                  - "9042"
                volumeMounts:
                  - name: sql
                    mountPath: /tmp/create_keyspace.cql
                    subPath: create_keyspace.cql
            volumes:
              - name: sql
                configMap:
                  name: "create-keyspace-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
                  items:
                    - key: create_keyspace.cql
                      path: create_keyspace.cql
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Wait for Cassandra keyspace creation job to complete
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    namespace: "{{ cassandra_namespace }}"
    name: "cassandra-keyspace-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
  register: job_info
  until: job_info.resources[0].status.succeeded is defined and job_info.resources[0].status.succeeded > 0
  retries: 10
  delay: 10
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clean up Cassandra keyspace creation job
  kubernetes.core.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    name: "cassandra-keyspace-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
    namespace: "{{ cassandra_namespace }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clean up keyspace creation SQL ConfigMap
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: "create-keyspace-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
    namespace: "{{ cassandra_namespace }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"
