---
- name: Get Cassandra admin password from secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ cassandra_namespace }}"
    name: cassandra
  register: cassandra_secret_info
  delegate_to: localhost
  become: false

- name: Set Cassandra admin password fact
  ansible.builtin.set_fact:
    cassandra_admin_password_decoded: "{{ cassandra_secret_info.resources[0].data['cassandra-password'] | b64decode }}"
  delegate_to: localhost
  become: false

- name: Render Cassandra user creation SQL from template
  ansible.builtin.template:
    src: create_user.cql.j2
    dest: "/tmp/create_user_{{ item.name }}.cql"
    mode: '0600'
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Create ConfigMap for Cassandra user creation SQL
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: "create-cassandra-user-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
        namespace: "{{ cassandra_namespace }}"
      data:
        create_user.cql: |
          {{ lookup('file', '/tmp/create_user_{{ item.name }}.cql') | indent(10) }}
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Run Cassandra user creation SQL in a temporary Cassandra client pod
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "cassandra-user-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
        namespace: "{{ cassandra_namespace }}"
      spec:
        backoffLimit: 1
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: cqlsh
                image: bitnami/cassandra:{{ cassandra_image_version }}
                command: ["cqlsh"]
                args:
                  - "-u"
                  - "{{ cassandra_admin_username }}"
                  - "-p"
                  - "{{ cassandra_admin_password_decoded }}"
                  - "-f"
                  - "/tmp/create_user.cql"
                  - "cassandra"
                  - "9042"
                volumeMounts:
                  - name: sql
                    mountPath: /tmp/create_user.cql
                    subPath: create_user.cql
            volumes:
              - name: sql
                configMap:
                  name: "create-cassandra-user-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
                  items:
                    - key: create_user.cql
                      path: create_user.cql
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Wait for Cassandra user creation job to complete
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    namespace: "{{ cassandra_namespace }}"
    name: "cassandra-user-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
  register: job_info
  until: job_info.resources[0].status.succeeded is defined and job_info.resources[0].status.succeeded > 0
  retries: 10
  delay: 10
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clean up Cassandra user creation job
  kubernetes.core.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    name: "cassandra-user-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
    namespace: "{{ cassandra_namespace }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clean up Cassandra user creation SQL ConfigMap
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: ConfigMap
    name: "create-cassandra-user-sql-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
    namespace: "{{ cassandra_namespace }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('cassandra.enabled', 'defined') | selectattr('cassandra.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"
