# Cert manager secrets
# K3s secrets
k3s_token: "REPLACE_WITH_YOUR_K3S_TOKEN"
k3s_local_kubeconfig: "{{ lookup('env', 'HOME') }}/.kube/k3s-config"
letsencrypt_email: "your@email.com"
# Harbor secrets
harbor_admin_password: "REPLACE_WITH_HARBOR_PASSWORD"
# harbor_domain: harbor.example.com # Your DNS name for Harbor
# Longhorn secrets
backblaze_key_id: "REPLACE_WITH_KEY_ID"
backblaze_application_key: "REPLACE_WITH_APPLICATION_KEY"
backblaze_bucket: "your-backup-bucket"
backblaze_region: "us-east-005"
backblaze_endpoint: "https://s3.{{backblaze_region}}.backblazeb2.com"
# Firewall configuration
firewall_open_k3s_ports: false
# Flux secrets
flux_github_username: your-github-username
flux_github_token: your-personal-access-token
