harbor_admin_password: "CHANGEME"
cert_manager_email: "changeme@example.com"
backblaze_key_id: "CHANGEME"
backblaze_application_key: "CHANGEME"
backblaze_bucket: "CHANGEME"
backblaze_region: "us-east-005"
backblaze_endpoint: "https://s3.{{backblaze_region}}.backblazeb2.com"
