# Variables to be defined before running the playbook
host_public_ip: "{{ lookup('env', 'HOST_PUBLIC_IP') }}"

# k3s cluster configuration
# Defaults: https://github.com/k3s-io/k3s-ansible/blob/master/roles/k3s_server/defaults/main.yml
k3s_server_extra_args: "--tls-san {{ host_public_ip }}"
k3s_agent_extra_args: "--tls-san {{ host_public_ip }}"
k3s_version: v1.33.1+k3s1
k3s_api_port: 6443
# Server configuration
ssh_port_rewritten: 2222 # The ansible role will make sure the server SSH port is set to this value

cassandra_namespace: cassandra
elasticsearch_namespace: elasticsearch

common_admin_username: "admin"
