- name: Install cert-manager
  ansible.builtin.include_role:
    name: cert_manager

- name: Install Longhorn
  ansible.builtin.include_role:
    name: longhorn

- name: Install Harbor
  ansible.builtin.include_role:
    name: harbor

- name: Install Flux
  ansible.builtin.include_role:
    name: flux

- name: Install GitHub Actions Runner and integrate with Flux repos
  ansible.builtin.include_role:
    name: github_actions
