---
- name: Setup monitoring namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Add monitoring Helm repos
  ansible.builtin.include_tasks: add_helm_repos.yml

- name: Install Prometheus
  ansible.builtin.include_tasks: install_prometheus.yml

- name: Install Grafana
  ansible.builtin.include_tasks: install_grafana.yml