---
- name: Add Argo CD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install Argo CD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    state: present
    wait: true
    wait_timeout: "{{ helm_install_timeout }}"
    values:
      imageUpdater:
        enabled: true
      configs:
        repositories:
          harbor:
            type: helm
            enableOCI: "true"
            name: "{{ harbor_hostname }}"
            url: "https://{{ harbor_hostname }}"
            username: "{{ harbor_admin_username }}"
            password: "{{ harbor_admin_password }}"
        params:
          server.insecure: true
        secret:
          argocdServerAdminPassword: "{{ argocd_admin_password | password_hash('bcrypt') }}"
          items:
            token: "{{ github_pat }}"
        notifiers:
          service.github: |
            token: $token
        notifications:
          templates: "{{ lookup('template', 'argocd_notification_template.yaml.j2') | from_yaml }}"
          triggers: "{{ lookup('template', 'argocd_notification_trigger.yaml.j2') | from_yaml }}"
