---
- name: Create GitHub token secret for Argo CD
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-git-auth
        namespace: argocd
        labels:
          argocd.argoproj.io/secret-type: repository
      stringData:
        type: git
        url: https://github.com
        username: "{{ argocd_github_username }}"
        password: "{{ github_pat }}"

- name: Ensure app namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ item.name }}"
  loop: "{{ self_saas_projects }}"

- name: Create Argo CD Application for each app repo
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: "{{ item.name }}"
        namespace: argocd
        annotations: "{{ lookup('template', 'argocd_application_annotations.yaml.j2') | from_yaml }}"
      spec:
        project: default
        source:
          repoURL: "{{ item.github_repo_http_url }}"
          targetRevision: HEAD
          path: "{{ item.path }}"
        destination:
          server: https://kubernetes.default.svc
          namespace: "{{ item.name }}"
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
  loop: "{{ self_saas_projects }}"
