- name: Check that the SSH public key exists on the control machine
  delegate_to: localhost
  become: false
  ansible.builtin.stat:
    path: "{{ ssh_public_key_to_authorize_on_target }}"
  register: ssh_pubkey_stat

- name: Fail if the SSH public key does not exist on the control machine
  delegate_to: localhost
  ansible.builtin.fail:
    msg: "The SSH public key file {{ ssh_public_key_to_authorize_on_target }} does not exist on the control machine."
  when: not ssh_pubkey_stat.stat.exists

- name: Ensure SSH public key is present for user 'ubuntu' on the remote machine
  ansible.posix.authorized_key:
    user: ubuntu
    state: present
    key: "{{ lookup('file', ssh_public_key_to_authorize_on_target) }}"

- name: Disable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication '
    line: 'PasswordAuthentication no'
    state: present
    backup: true

- name: Allow new SSH port in UFW
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port_rewritten | default(2222) }}"

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart SSH service
  ansible.builtin.service:
    name: ssh
    state: restarted
