- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443

- name: Allow K3s API port if requested
  community.general.ufw:
    rule: allow
    port: "{{ k3s_api_port | default(6443) }}"
  when: firewall_open_k3s_ports | default(false)

- name: Allow SMTP (25) in UFW
  community.general.ufw:
    rule: allow
    port: 25
    proto: tcp

- name: Allow SMTPS (465) in UFW
  community.general.ufw:
    rule: allow
    port: 465
    proto: tcp

- name: Allow Submission (587) in UFW
  community.general.ufw:
    rule: allow
    port: 587
    proto: tcp

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
