---
- name: Install UFW
  ansible.builtin.include_tasks: install_ufw.yml

- name: Configure SSH
  ansible.builtin.include_tasks: configure_ssh.yml

- name: Configure UFW
  ansible.builtin.include_tasks: configure_ufw.yml