- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443

- name: Allow K3s API port if requested
  community.general.ufw:
    rule: allow
    port: "{{ k3s_api_port | default(6443) }}"
  when: firewall_open_k3s_ports | default(false)

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
