- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Warn if ddns_domain_allowed_ssh is not set (SSH will be open to anyone!)
  ansible.builtin.debug:
    msg: |
      #############################################################
      #  WARNING: SSH is open to ANYONE!                         #
      #  This is INSECURE.                                       #
      #  Set ddns_domain_allowed_ssh to restrict SSH access.      #
      #  Consider using a Dynamic DNS service.                   #
      #############################################################
    warn: true
  when: ddns_domain_allowed_ssh is not defined

- name: Resolve DDNS domain to IP
  ansible.builtin.set_fact:
    resolved_ssh_ip: "{{ lookup('ansible.builtin.dig', ddns_domain_allowed_ssh) }}"
  when: ddns_domain_allowed_ssh is defined

- name: Allow SSH from resolved IP
  community.general.ufw:
    rule: allow
    port: 22
    from_ip: "{{ resolved_ssh_ip }}"
  when: ddns_domain_allowed_ssh is defined

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443

- name: Allow K3s API port if requested
  community.general.ufw:
    rule: allow
    port: "{{ k3s_api_port | default(6443) }}"
  when: firewall_open_k3s_ports | default(false)

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
