- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
    update_cache: true

- name: Allow SSH
  community.general.ufw:
    rule: allow
    port: 22

- name: Allow HTTP
  community.general.ufw:
    rule: allow
    port: 80

- name: Allow HTTPS
  community.general.ufw:
    rule: allow
    port: 443

- name: Enable UFW
  community.general.ufw:
    state: enabled
    policy: deny
