- name: Install k3s (latest stable)
  shell: |
    curl -sfL https://get.k3s.io | sh -s - --docker
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s service to be active
  systemd:
    name: k3s
    state: started
    enabled: yes

- name: Get kubeconfig
  slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig

- name: Set KUBECONFIG for future tasks
  set_fact:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
