---
- name: Setup GitHub Actions controller
  ansible.builtin.include_tasks: setup_controller.yml

- name: Deploy GitHub Actions runners
  ansible.builtin.include_tasks: deploy_runners.yml

- name: Setup RBAC for GitHub Actions
  ansible.builtin.include_tasks: setup_rbac.yml