- name: Add actions-runner-controller Helm repository
  kubernetes.core.helm_repository:
    name: actions-runner-controller
    repo_url: https://actions-runner-controller.github.io/actions-runner-controller

- name: Ensure actions-runner-system namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: actions-runner-system

- name: Create GitHub token secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: controller-manager-gh-secret
        namespace: actions-runner-system
      stringData:
        github_token: "{{ github_pat }}"

- name: Install actions-runner-controller via Helm
  kubernetes.core.helm:
    name: actions-runner-controller
    chart_ref: actions-runner-controller/actions-runner-controller
    release_namespace: actions-runner-system
    create_namespace: true
    values:
      authSecret:
        create: false
        name: controller-manager-gh-secret
      podLabels:
        control-plane: controller-manager
    wait: true
    wait_timeout: 5m

- name: Get Harbor TLS secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ harbor_namespace }}"
    name: "{{ harbor_tls_secret_name }}"
  register: harbor_tls_secret

- name: Create harbor-ca secret in actions-runner-system
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: harbor-ca
        namespace: actions-runner-system
      data:
        ca.crt: "{{ harbor_tls_secret.resources[0].data['ca.crt'] }}"

- name: Deploy GitHub Actions Runner for each app repo
  ansible.builtin.template:
    src: runnerdeployment.yaml.j2
    dest: "/tmp/runnerdeployment_{{ item.name }}.yaml"
    mode: '0644'
  loop: "{{ self_saas_projects }}"
  register: rendered_runner_deployments

- name: Apply runner deployments
  kubernetes.core.k8s:
    state: present
    src: "{{ item.dest }}"
  loop: "{{ rendered_runner_deployments.results }}"

# Steps to allow running kubectl commands in GitHub Actions workflows
- name: Create ServiceAccount for GitHub Actions runners
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: github-actions-runner
        namespace: actions-runner-system

- name: Create ClusterRole for GitHub Actions runners (admin access)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: github-actions-runner-admin
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]

- name: Bind ServiceAccount to ClusterRole
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: github-actions-runner-admin-binding
      subjects:
        - kind: ServiceAccount
          name: github-actions-runner
          namespace: actions-runner-system
      roleRef:
        kind: ClusterRole
        name: github-actions-runner-admin
        apiGroup: rbac.authorization.k8s.io

- name: Create ServiceAccount, Role, and RoleBinding for each project
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "github-actions-runner-{{ item.name }}"
        namespace: "{{ item.name }}"
  loop: "{{ self_saas_projects }}"

- name: Create Role for kubectl access in project namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: github-actions-runner-role
        namespace: "{{ item.name }}"
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]
  loop: "{{ self_saas_projects }}"

- name: Bind ServiceAccount to Role in project namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: github-actions-runner-rolebinding
        namespace: "{{ item.name }}"
      subjects:
        - kind: ServiceAccount
          name: "github-actions-runner-{{ item.name }}"
          namespace: "{{ item.name }}"
      roleRef:
        kind: Role
        name: github-actions-runner-role
        apiGroup: rbac.authorization.k8s.io
  loop: "{{ self_saas_projects }}"
