- name: Install k3s (latest stable)
  ansible.builtin.shell: |
    curl -sfL https://get.k3s.io | sh -s - --docker
  args:
    creates: /usr/local/bin/k3s

- name: Wait for k3s service to be active
  ansible.builtin.systemd:
    name: k3s
    state: started
    enabled: true

- name: Get kubeconfig
  ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubeconfig

- name: Set KUBECONFIG for future tasks
  ansible.builtin.set_fact:
    kubeconfig_path: /etc/rancher/k3s/k3s.yaml
