---
- name: Create Elasticsearch index for project
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "elasticsearch-index-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
        namespace: "{{ elasticsearch_namespace }}"
      spec:
        backoffLimit: 1
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: curl
                image: curlimages/curl:8.7.1
                command:
                  - sh
                  - -c
                  - |
                    curl -X PUT "http://elasticsearch-master:9200/{{ item.name | lower | regex_replace('[^a-z0-9_]', '_') }}" \
                      -u "{{ elasticsearch_username }}:{{ elasticsearch_password }}" \
                      -H 'Content-Type: application/json' -d '{}'
                env:
                  - name: ELASTICSEARCH_USERNAME
                    value: "{{ elasticsearch_username }}"
                  - name: ELASTICSEARCH_PASSWORD
                    value: "{{ elasticsearch_password }}"
    delegate_to: localhost
    run_once: true
  loop: "{{ self_saas_projects | selectattr('elasticsearch.enabled', 'defined') | selectattr('elasticsearch.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Wait for Elasticsearch index creation job to complete
  kubernetes.core.k8s_info:
    api_version: batch/v1
    kind: Job
    namespace: "{{ elasticsearch_namespace }}"
    name: "elasticsearch-index-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
  register: job_info
  until: job_info.resources[0].status.succeeded is defined and job_info.resources[0].status.succeeded > 0
  retries: 10
  delay: 10
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('elasticsearch.enabled', 'defined') | selectattr('elasticsearch.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"

- name: Clean up Elasticsearch index creation job
  kubernetes.core.k8s:
    state: absent
    api_version: batch/v1
    kind: Job
    name: "elasticsearch-index-creator-{{ item.name | lower | regex_replace('[^a-z0-9-]', '-') }}"
    namespace: "{{ elasticsearch_namespace }}"
  delegate_to: localhost
  run_once: true
  loop: "{{ self_saas_projects | selectattr('elasticsearch.enabled', 'defined') | selectattr('elasticsearch.enabled') | list }}"
  loop_control:
    label: "{{ item.name }}"
