- name: Render project database SQL from template
  ansible.builtin.template:
    src: create_project_databases.sql.j2
    dest: /tmp/create_project_databases.sql
    mode: "0600"
  delegate_to: localhost
  run_once: true

- name: Create ConfigMap for project database SQL
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: project-databases-sql
        namespace: "{{ postgres_namespace }}"
      data:
        create_project_databases.sql: |
          {{ lookup('file', '/tmp/create_project_databases.sql') | indent(10) }}
  delegate_to: localhost
  run_once: true

- name: Ensure previous psql-client-create-databases pod is absent before creation
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Pod
    name: psql-client-create-databases
    namespace: "{{ postgres_namespace }}"
  delegate_to: localhost
  run_once: true

- name: Run database creation SQL in a temporary Postgres client pod
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Pod
      metadata:
        name: psql-client-create-databases
        namespace: "{{ postgres_namespace }}"
      spec:
        restartPolicy: Never
        containers:
          - name: psql
            image: "docker.io/bitnami/postgresql:{{ postgres_client_pod_image_tag }}"
            env:
              - name: PGPASSWORD
                value: "{{ postgres_admin_password }}"
            command: ["psql"]
            args:
              - "-h"
              - "postgres-postgresql"
              - "-U"
              - "postgres"
              - "-f"
              - "/tmp/create_project_databases.sql"
            volumeMounts:
              - name: sql
                mountPath: /tmp/create_project_databases.sql
                subPath: create_project_databases.sql
        volumes:
          - name: sql
            configMap:
              name: project-databases-sql
              items:
                - key: create_project_databases.sql
                  path: create_project_databases.sql
  delegate_to: localhost
  run_once: true

- name: Wait for psql-client-create-databases pod to complete
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: "{{ postgres_namespace }}"
    name: psql-client-create-databases
  register: pod_info_db
  until: pod_info_db.resources[0].status.phase == 'Succeeded'
  retries: 5
  delay: 6
  delegate_to: localhost
  run_once: true
