---
- name: Setup postgres namespace
  ansible.builtin.include_tasks: setup_namespace.yml

- name: Install postgres
  ansible.builtin.include_tasks: install.yml

- name: Create postgres databases
  ansible.builtin.include_tasks: create_databases.yml

- name: Create postgres users
  ansible.builtin.include_tasks: create_users.yml

- name: Grant user migration permissions
  ansible.builtin.include_tasks: create_user_migration_permissions.yml