- name: Sanitize NodeHosts to remove IPv6 entries before patching CoreDNS
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ConfigMap
    namespace: kube-system
    name: coredns
  register: coredns_cm_for_sanitize

- name: Set sanitized NodeHosts (IPv4 only)
  ansible.builtin.set_fact:
    sanitized_nodehosts: |
      {% for line in coredns_cm_for_sanitize.resources[0].data.get('NodeHosts', '').splitlines() %}
      {% set parts = line.split() %}
      {% if parts and (parts[0] | default('')).count('.') == 3 %}{{ line }}
      {% endif %}
      {% endfor %}

- name: Patch CoreDNS to use DNSSEC-validating upstreams and preserve NodeHosts (IPv4 only)
  kubernetes.core.k8s:
    state: present
    namespace: kube-system
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: coredns
      data:
        Corefile: |
          .:53 {
              errors
              health
              ready
              kubernetes cluster.local in-addr.arpa ip6.arpa {
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
              }
              hosts /etc/coredns/NodeHosts {
                  ttl 60
                  reload 15s
                  fallthrough
              }
              forward . 1.1.1.1 9.9.9.9
              dnssec
              cache 30
              loop
              reload
              loadbalance
          }
        NodeHosts: "{{ sanitized_nodehosts }}"

- name: Restart CoreDNS to apply changes
  kubernetes.core.k8s:
    api_version: v1
    kind: Pod
    namespace: kube-system
    label_selectors:
      - k8s-app=coredns
    state: absent
    wait: true
