---
- name: Install cert-manager
  ansible.builtin.include_tasks: install.yml

- name: Setup cert-manager ClusterIssuer
  ansible.builtin.include_tasks: setup_cluster_issuer.yml

- name: Configure CoreDNS
  ansible.builtin.include_tasks: configure_coredns.yml